apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    stack: monitoring
    component: alertmanager
spec:
  project: default
  source:
    repoURL: https://github.com/pentago/monitoring.git
    targetRevision: HEAD
    path: 'alertmanager'
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
