{
 "title": "Aurora Hardware Resources",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up==1)" }
   ]
  },
  {
   "title": "DOWN RECENTLY",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 1, "y": 0 },
   "targets": [
    { "expr": "count by (name) (up==0)", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "DISKS < 5GB",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{volume!~\"HarddiskVolume.+\"} < 5000000000",
     "legendFormat": "{{name}} {{volume}}"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} < 5000000000",
     "legendFormat": "{{name}} {{volume}}"
    }
   ]
  },
  {
   "title": "∑ CPU%",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(1 - avg by (name) (rate(windows_cpu_time_total{mode=\"idle\"}[$interval])))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "100*(1 - avg by (name) (rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "∑ RAM",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "windows_cs_physical_memory_bytes - windows_os_physical_memory_free_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "----------------------- CPU -----------------------",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (name) (rate(windows_cpu_time_total{mode=\"idle\"}[$interval])))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "100 * (1 - avg by (name) (rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "100 * (1 - avg by (name) (rate(node_cpu{mode=\"idle\"}[$interval])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "----------------------- RAM -----------------------",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable / (node_memory_MemTotal)))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "----------------------- Disk -----------------------",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{volume!~\"HarddiskVolume.+\"}",
     "legendFormat": "{{volume}} {{name}}"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{mountpoint}} {{name}}"
    },
    {
     "expr": "node_filesystem_avail{mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "{{mountpoint}} {{name}}"
    },
    {
     "expr": "node_filesystem_avail{mountpoint=\"/var\",fstype!=\"rootfs\"}",
     "legendFormat": "{{mountpoint}} {{name}}"
    }
   ]
  }
 ]
}
{
 "title": "Aurora Services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 18, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "windows_service_info * on(exported_name,job) group_left(start_mode) (windows_service_start_mode{start_mode!=\"disabled\"} == 1)"
    }
   ]
  },
  {
   "title": "Hekla Dev Queues",
   "type": "table",
   "gridPos": { "h": 27, "w": 9, "x": 7, "y": 0 },
   "targets": [
    { "expr": "query_result_hekla_queues" }
   ]
  },
  {
   "title": "Docker Containers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}",
     "legendFormat": "running"
    },
    {
     "expr": "engine_daemon_container_states_containers{state=\"stopped\"}",
     "legendFormat": "stopped"
    },
    {
     "expr": "engine_daemon_container_states_containers{state=\"paused\"}",
     "legendFormat": "paused"
    }
   ]
  },
  {
   "title": "Docker Containers",
   "type": "table",
   "gridPos": { "h": 23, "w": 8, "x": 16, "y": 4 },
   "targets": [
    { "expr": "docker_container_running_state" },
    { "expr": "docker_container_restart_count" },
    {
     "expr": "docker_container_start_time_seconds * 1000"
    }
   ]
  },
  {
   "title": "App Pools",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "windows_iis_current_application_pool_state{app!=\"MedicorApppool\"} > 0"
    }
   ]
  }
 ]
}
{
 "title": "BorderHealth API",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{instance=\"screening.covid.is:80\"}[$interval]  )) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Unprocessed Lab Results",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "covid_unprocessed_labresults" }
   ]
  },
  {
   "title": "Unsent Barcodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "covid_unsent_barcods" }
   ]
  },
  {
   "title": "Unprocessed Positive Lab Results",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "covid_unprocessed_postive_labresults"
    }
   ]
  },
  {
   "title": "Unsent Symptoms Barcodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "covid_unsent_symptom_barcods" }
   ]
  },
  {
   "title": "GC collection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total{instance=\"screening.covid.is:80\"}[$interval])",
     "legendFormat": "Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_in_progress{instance=\"screening.covid.is:80\"}[$interval]  )) by (controller)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_handles{instance=\"screening.covid.is:80\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{instance=\"screening.covid.is:80\"} /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{instance=\"screening.covid.is:80\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{instance=\"screening.covid.is:80\"} /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Start time of the process",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 47 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"screening.covid.is:80\"} * 1000"
    }
   ]
  }
 ]
}
{
 "title": "HeilsuveraAPI - Test",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{instance=\"docker.dev.hc.local:9101\"}[$interval]  )) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "active_users" }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_in_progress{instance=\"docker.dev.hc.local:9101\"}[$interval]  )) by (controller)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC collection count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total{instance=\"docker.dev.hc.local:9101\"}[$interval])",
     "legendFormat": "Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{instance=\"docker.dev.hc.local:9101\"} /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_handles{instance=\"docker.dev.hc.local:9101\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{instance=\"docker.dev.hc.local:9101\"} /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{instance=\"docker.dev.hc.local:9101\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Start time of the process",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 31 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"docker.dev.hc.local:9101\"} * 1000"
    }
   ]
  }
 ]
}
{
 "title": "Hekla Critical Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Vera incoming messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hekla_service_incoming_messages{nodeid=\"VERA\",serviceid!~\"PATIENT_PORTAL_REQUEST\",serviceid!~\"COVID_DEPARTURE_CERTIFICATE\",serviceid!~\"SVALA_VACCINATIONS_SERVICE\"}",
     "legendFormat": "{{serviceid}}"
    }
   ]
  },
  {
   "title": "Hekla CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hekla_cpu_usage" }
   ]
  },
  {
   "title": "Hekla Svala Incoming Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hekla_service_incoming_messages{nodeid=\"SVALA\",serviceid=~\"COVID.*\"} or hekla_service_incoming_messages{nodeid=\"SVALA\",serviceid=~\"DECODE.*\"} or hekla_service_incoming_messages{nodeid=\"SVALA\",serviceid=~\"QUARANTINE.*\"} or hekla_service_incoming_messages{nodeid=\"SVALA\",serviceid=~\"PRESCRIPTION.*\"} or hekla_service_incoming_messages{nodeid=\"SVALA\",serviceid=\"SVALA_PRESCRIPTIONS_SERVICE\"}",
     "legendFormat": "{{serviceid}}"
    }
   ]
  },
  {
   "title": "Hekla used memory (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100*(1-hekla_broker_available_memory/hekla_broker_total_memory)"
    }
   ]
  },
  {
   "title": "Vera Queue Online",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hekla_service_status{nodeid=\"VERA\"}",
     "legendFormat": "{{nodeid}} {{serviceid}}"
    }
   ]
  },
  {
   "title": "Mirroring State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hekla_mirroring_State" }
   ]
  },
  {
   "title": "Hekla Queue Online",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hekla_service_status{nodeid=\"SVALA\"} or hekla_service_status{serviceid=~\"COVID.*\", nodeid=\"VERA\"} or hekla_service_status{serviceid=~\"COVID.*\", nodeid=\"LANDLAEKNIR\"}\n",
     "legendFormat": "{{serviceid}}"
    }
   ]
  }
 ]
}
{
 "title": "Traefik",
 "description": "Simple dashboard for Traefik 2",
 "tags": [
  "traefik",
  "load-balancer",
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job:", "query": "traefik" },
   {
    "name": "protocol",
    "label": "Service:",
    "query": {
     "query": "label_values(traefik_service_requests_total, protocol)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total[$interval])) by (service) ",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{protocol=\"http\"}) / sum(traefik_entrypoint_requests_total{protocol=\"http\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "404 Error Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"404\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "503 Error count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"503\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Top 5 $protocol return code",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(traefik_service_requests_total{protocol=~\"$protocol\"}) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 8 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Bad Status Code Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"404\",method=\"GET\",protocol=~\"$protocol\"}[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[$interval]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Used sockets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Access to services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{protocol=~\"http|https\"}[$interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "ENTRYPOINT - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "SERVICE - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Status Code Count ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{protocol=~\"$protocol\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}