apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: grafana
    stack: monitoring
spec:
  project: default
  source:
    helm:
      valueFiles: values.yaml
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.43.5
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
