apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: grafana
    stack: monitoring
spec:
  project: default

  source:
    repoURL: https://github.com/pentago/monitoring.git
    targetRevision: HEAD
    path: 'charts/grafana'
    helm:
      # releaseName: grafana
      valueFiles:
        - values.yaml

  destination:
    namespace: observability
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
