apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: grafana
    stack: monitoring
spec:
  project: default
  revisionHistoryLimit: 10

  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.43.5  # For Helm, this refers to the chart version.
    path: grafana

    chart: grafana # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
    helm:
      version: v3
      releaseName: grafana
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
